SP500 = {
    "Basic Materials": [
        "LIN",
        "SHW",
        "APD",
        "ECL",
        "DD",
        "NEM",
        "DOW",
        "FCX",
        "PPG",
        "CTVA.N",
        "LYB",
        "VMC",
        "NUE",
        "MLM",
        "CE",
        "FMC",
        "ALB",
        "EMN",
        "IFF",
        "MOS",
        "CF"
    ],
    "Communication Services": [
        "FB.OQ",
        "GOOGL.OQ",
        "GOOG.O",
        "DIS",
        "VZ",
        "NFLX.OQ",
        "CMCSA.OQ",
        "T",
        "CHTR.OQ",
        "TMUS.OQ",
        "ATVI.OQ",
        "TWTR.N",
        "EA.OQ",
        "TTWO.OQ",
        "VIAC.O",
        "OMC",
        "LYV",
        "LUMN.N",
        "FOXA.OQ",
        "IPG",
        "DISCK.O",
        "DISH.OQ",
        "NWSA.OQ",
        "DISCA.OQ",
        "FOX.TA",
        "NWS.O"
    ],
    "Consumer Cyclical": [
        "AMZN.OQ",
        "HD",
        "NKE",
        "MCD",
        "LOW",
        "SBUX.OQ",
        "BKNG.OQ",
        "TJX",
        "GM",
        "ROST.OQ",
        "CMG",
        "F",
        "EBAY.OQ",
        "MAR.OQ",
        "APTV.N",
        "ORLY.OQ",
        "YUM",
        "BLL",
        "HLT.N",
        "VFC",
        "AZO",
        "DHI",
        "BBY",
        "ETSY.OQ",
        "LEN",
        "IP",
        "LVS",
        "AMCR.N",
        "TSCO.OQ",
        "EXPE.OQ",
        "KMX",
        "DRI",
        "ULTA.OQ",
        "DPZ",
        "NVR",
        "POOL.OQ",
        "GPC",
        "TIF",
        "RCL",
        "PKG",
        "MGM",
        "FBHS.N",
        "PHM",
        "WHR",
        "HAS.OQ",
        "WRK",
        "CCL",
        "AAP",
        "WYNN.OQ",
        "LKQ.OQ",
        "BWA",
        "LB",
        "ROL",
        "TPR",
        "MHK",
        "NCLH.N",
        "SEE",
        "PVH",
        "LEG",
        "RL",
        "HBI",
        "GPS",
        "UAA",
        "UA"
    ],
    "Consumer Defensive": [
        "PG",
        "KO",
        "WMT",
        "PEP.OQ",
        "COST.OQ",
        "PM",
        "TGT",
        "MDLZ.OQ",
        "MO",
        "CL",
        "EL",
        "DG",
        "KMB",
        "SYY",
        "STZ",
        "GIS",
        "MNST.OQ",
        "ADM",
        "DLTR.OQ",
        "CLX",
        "KR",
        "MKC",
        "KHC.OQ",
        "HSY",
        "CHD",
        "TSN",
        "CAG",
        "K",
        "BFb.N",
        "HRL",
        "SJM",
        "LW",
        "CPB",
        "TAP",
        "NWL.OQ"
    ],
    "Energy": [
        "XOM",
        "CVX",
        "COP",
        "SLB",
        "EOG",
        "PSX",
        "KMI",
        "MPC",
        "WMB",
        "VLO",
        "PXD",
        "OKE",
        "HAL",
        "OXY",
        "HES",
        "BKR",
        "CXO",
        "FANG.OQ",
        "COG",
        "DVN",
        "APA.N",
        "MRO",
        "NOV",
        "FTI",
        "HFC"
    ],
    "Financial Services": [
        "BRKb.N",
        "JPM",
        "V.N",
        "MA",
        "PYPL.OQ",
        "BAC",
        "C",
        "WFC",
        "BLK",
        "MS",
        "GS",
        "AXP",
        "SPGI.N",
        "SCHW.N",
        "CB",
        "CME.OQ",
        "TFC",
        "ICE",
        "USB",
        "PNC",
        "MMC",
        "PGR",
        "AON",
        "MCO",
        "COF",
        "MSCI.N",
        "MET",
        "TRV",
        "TROW.OQ",
        "ALL",
        "AIG",
        "BK",
        "PRU",
        "AFL",
        "WLTW.OQ",
        "DFS",
        "STT",
        "AJG",
        "FRC",
        "AMP",
        "MKTX.OQ",
        "FITB.OQ",
        "NTRS.OQ",
        "SIVB.OQ",
        "SYF",
        "HIG",
        "MTB",
        "KEY",
        "RF",
        "CFG",
        "NDAQ.OQ",
        "CINF.OQ",
        "HBAN.OQ",
        "PFG.OQ",
        "RJF",
        "L",
        "CBOE.Z",
        "WU",
        "RE",
        "WRB",
        "GL",
        "LNC",
        "AIZ",
        "CMA",
        "ZION.OQ",
        "BEN",
        "IVZ",
        "PBCT.OQ",
        "UNM",
        "AIV"
    ],
    "Healthcare": [
        "JNJ",
        "UNH",
        "PFE",
        "MRK",
        "ABT",
        "ABBV.N",
        "TMO",
        "MDT",
        "DHR",
        "BMY",
        "LLY",
        "AMGN.OQ",
        "ISRG.OQ",
        "CVS",
        "ANTM.N",
        "SYK",
        "ZTS",
        "CI",
        "GILD.OQ",
        "BDX",
        "VRTX.OQ",
        "EW",
        "ILMN.OQ",
        "HUM",
        "REGN.OQ",
        "BSX",
        "HCA",
        "BAX",
        "IDXX.OQ",
        "BIIB.OQ",
        "ALGN.OQ",
        "A",
        "CNC",
        "ALXN.OQ",
        "DXCM.OQ",
        "IQV",
        "ZBH",
        "RMD",
        "WBA.OQ",
        "MCK",
        "MTD",
        "CERN.OQ",
        "VTRS.RTS",
        "WST",
        "LH",
        "HOLX.OQ",
        "TFX",
        "COO",
        "CTLT.N",
        "INCY.OQ",
        "DGX",
        "PKI",
        "CAH",
        "VAR",
        "WAT",
        "STE",
        "ABC",
        "ABMD.OQ",
        "BIO",
        "XRAY.OQ",
        "UHS",
        "HSIC.OQ",
        "DVA",
        "PRGO.N"
    ],
    "Industrials": [
        "HON",
        "UNP",
        "UPS",
        "BA",
        "RTX.CO",
        "MMM",
        "CAT",
        "GE",
        "LMT",
        "DE",
        "ADP.OQ",
        "FDX",
        "CSX.OQ",
        "ITW",
        "NSC",
        "GPN",
        "EMR",
        "NOC",
        "ETN",
        "WM",
        "ROP",
        "LHX",
        "PH",
        "JCI",
        "TTG.L",
        "CMI",
        "VRSK.OQ",
        "INFO.N",
        "TDG",
        "CARRA.MI",
        "CTAS.OQ",
        "PAYX.OQ",
        "PCAR.OQ",
        "SWK",
        "ROK",
        "FAST.OQ",
        "LUV",
        "AME",
        "ZOT.MC",
        "DAL",
        "CPRT.OQ",
        "EFX",
        "RSG",
        "ODFL.OQ",
        "KSU",
        "GWW",
        "DOV",
        "XYL",
        "IR",
        "URI",
        "EXPD.OQ",
        "IEX",
        "MAS",
        "J",
        "UAL.OQ",
        "WAB",
        "AVY",
        "CHRW.OQ",
        "JBHT.OQ",
        "TXT",
        "ALLE.N",
        "HWM",
        "PWR",
        "SNA",
        "PNR",
        "AAL.OQ",
        "AOS",
        "RHI",
        "HII",
        "NLSN.N",
        "ALK",
        "FLS"
    ],
    "Real Estate": [
        "AMT",
        "PLD",
        "CCI",
        "EQIX.OQ",
        "DLR",
        "PSA",
        "SBAC.OQ",
        "SPG",
        "WELL.N",
        "WY",
        "AVB",
        "CBRE.N",
        "O",
        "ARE",
        "EQR",
        "VTR",
        "PEAK.N",
        "ESS",
        "DRE",
        "EXR",
        "MAA",
        "BXP",
        "UDR",
        "HST.N",
        "IRM",
        "REG.OQ",
        "KIM",
        "FRT",
        "VNO",
        "AIRC.L",
        "SLG"
    ],
    "Technology": [
        "AAPL.OQ",
        "MSFT.OQ",
        "NVDA.OQ",
        "ADBE.OQ",
        "INTC.OQ",
        "CRM",
        "CSCO.OQ",
        "AVGO.OQ",
        "QCOM.OQ",
        "ACN",
        "TXN.OQ",
        "ORCL.N",
        "AMD.OQ",
        "IBM",
        "NOW",
        "INTU.OQ",
        "FIS",
        "MU.OQ",
        "AMAT.OQ",
        "LRCX.OQ",
        "ADSK.OQ",
        "FISV.OQ",
        "ADI.OQ",
        "CTSH.OQ",
        "KLAC.OQ",
        "APH",
        "TEL",
        "SNPS.OQ",
        "XLNX.OQ",
        "CDNS.OQ",
        "MCHP.OQ",
        "HPQ",
        "ANSS.OQ",
        "MSI",
        "GLW",
        "SWKS.OQ",
        "FLT",
        "KEYS.N",
        "FTV",
        "MXIM.OQ",
        "VRSN.OQ",
        "PAYC.N",
        "ZBRA.OQ",
        "TER.OQ",
        "CDW.OQ",
        "FINT.TO",
        "QRVO.OQ",
        "TYL",
        "GRMN.OQ",
        "BR",
        "AKAM.OQ",
        "CTXS.OQ",
        "WDC.OQ",
        "HPE",
        "ANET.N",
        "STX.OQ",
        "NTAP.OQ",
        "TDY",
        "LDOS.N",
        "IT",
        "JKHY.OQ",
        "NLOK.OQ",
        "FFIV.OQ",
        "IPGP.OQ"
    ],
    "Utilities": [
        "NEE",
        "DUK",
        "SO",
        "D",
        "AEP.O",
        "EXC.OQ",
        "SRE",
        "XEL.OQ",
        "ES",
        "WEC",
        "PEG",
        "AWK",
        "EIX",
        "ED",
        "DTE",
        "PPL",
        "ETR",
        "AEE",
        "CMS",
        "FE",
        "AES",
        "LNT.OQ",
        "EVRG.N",
        "ATO",
        "CNP",
        "PNW",
        "NI",
        "NRG"
    ]
}

SP500_map = {
    "Basic Materials": {
        "ALB": "ALB",
        "APD": "APD",
        "CE": "CE",
        "CF": "CF",
        "CTVA": "CTVA.N",
        "DD": "DD",
        "DOW": "DOW",
        "ECL": "ECL",
        "EMN": "EMN",
        "FCX": "FCX",
        "FMC": "FMC",
        "IFF": "IFF",
        "LIN": "LIN",
        "LYB": "LYB",
        "MLM": "MLM",
        "MOS": "MOS",
        "NEM": "NEM",
        "NUE": "NUE",
        "PPG": "PPG",
        "SHW": "SHW",
        "VMC": "VMC"
    },
    "Communication Services": {
        "ATVI": "ATVI.OQ",
        "CHTR": "CHTR.OQ",
        "CMCSA": "CMCSA.OQ",
        "DIS": "DIS",
        "DISCA": "DISCA.OQ",
        "DISCK": "DISCK.O",
        "DISH": "DISH.OQ",
        "EA": "EA.OQ",
        "FB": "FB.OQ",
        "FOX": "FOX.TA",
        "FOXA": "FOXA.OQ",
        "GOOG": "GOOG.O",
        "GOOGL": "GOOGL.OQ",
        "IPG": "IPG",
        "LUMN": "LUMN.N",
        "LYV": "LYV",
        "NFLX": "NFLX.OQ",
        "NWS": "NWS.O",
        "NWSA": "NWSA.OQ",
        "OMC": "OMC",
        "T": "T",
        "TMUS": "TMUS.OQ",
        "TTWO": "TTWO.OQ",
        "TWTR": "TWTR.N",
        "VIAC": "VIAC.O",
        "VZ": "VZ"
    },
    "Consumer Cyclical": {
        "AAP": "AAP",
        "AMCR": "AMCR.N",
        "AMZN": "AMZN.OQ",
        "APTV": "APTV.N",
        "AZO": "AZO",
        "BBY": "BBY",
        "BKNG": "BKNG.OQ",
        "BLL": "BLL",
        "BWA": "BWA",
        "CCL": "CCL",
        "CMG": "CMG",
        "DHI": "DHI",
        "DPZ": "DPZ",
        "DRI": "DRI",
        "EBAY": "EBAY.OQ",
        "ETSY": "ETSY.OQ",
        "EXPE": "EXPE.OQ",
        "F": "F",
        "FBHS": "FBHS.N",
        "GM": "GM",
        "GPS": "GPS",
        "Gpc": "GPC",
        "HAS": "HAS.OQ",
        "HBI": "HBI",
        "HD": "HD",
        "HLT": "HLT.N",
        "IP": "IP",
        "KMX": "KMX",
        "LB": "LB",
        "LEG": "LEG",
        "LEN": "LEN",
        "LKQ": "LKQ.OQ",
        "LOW": "LOW",
        "LVS": "LVS",
        "MAR": "MAR.OQ",
        "MCD": "MCD",
        "MGM": "MGM",
        "MHK": "MHK",
        "NCLH": "NCLH.N",
        "NKE": "NKE",
        "NVR": "NVR",
        "ORLY": "ORLY.OQ",
        "PHM": "PHM",
        "PKG": "PKG",
        "POOL": "POOL.OQ",
        "PVH": "PVH",
        "RCL": "RCL",
        "RL": "RL",
        "ROL": "ROL",
        "ROST": "ROST.OQ",
        "SBUX": "SBUX.OQ",
        "SEE": "SEE",
        "TIF": "TIF",
        "TJX": "TJX",
        "TPR": "TPR",
        "TSCO": "TSCO.OQ",
        "UA": "UA",
        "UAA": "UAA",
        "ULTA": "ULTA.OQ",
        "VFC": "VFC",
        "WHR": "WHR",
        "WRK": "WRK",
        "WYNN": "WYNN.OQ",
        "YUM": "YUM"
    },
    "Consumer Defensive": {
        "ADM": "ADM",
        "BF-B": "BFb.N",
        "CAG": "CAG",
        "CHD": "CHD",
        "CL": "CL",
        "CLX": "CLX",
        "COST": "COST.OQ",
        "CPB": "CPB",
        "DG": "DG",
        "DLTR": "DLTR.OQ",
        "EL": "EL",
        "GIS": "GIS",
        "HRL": "HRL",
        "HSY": "HSY",
        "K": "K",
        "KHC": "KHC.OQ",
        "KMB": "KMB",
        "KO": "KO",
        "KR": "KR",
        "LW": "LW",
        "MDLZ": "MDLZ.OQ",
        "MKC": "MKC",
        "MNST": "MNST.OQ",
        "MO": "MO",
        "NWL": "NWL.OQ",
        "PEP": "PEP.OQ",
        "PG": "PG",
        "PM": "PM",
        "SJM": "SJM",
        "STZ": "STZ",
        "SYY": "SYY",
        "TAP": "TAP",
        "TGT": "TGT",
        "TSN": "TSN",
        "WMT": "WMT"
    },
    "Energy": {
        "APA": "APA.N",
        "BKR": "BKR",
        "COG": "COG",
        "COP": "COP",
        "CVX": "CVX",
        "CXO": "CXO",
        "DVN": "DVN",
        "EOG": "EOG",
        "FANG": "FANG.OQ",
        "FTI": "FTI",
        "HAL": "HAL",
        "HES": "HES",
        "HFC": "HFC",
        "KMI": "KMI",
        "MPC": "MPC",
        "MRO": "MRO",
        "NOV": "NOV",
        "OKE": "OKE",
        "OXY": "OXY",
        "PSX": "PSX",
        "PXD": "PXD",
        "SLB": "SLB",
        "VLO": "VLO",
        "WMB": "WMB",
        "XOM": "XOM"
    },
    "Financial Services": {
        "AFL": "AFL",
        "AIG": "AIG",
        "AIV": "AIV",
        "AIZ": "AIZ",
        "AJG": "AJG",
        "ALL": "ALL",
        "AMP": "AMP",
        "AON": "AON",
        "AXP": "AXP",
        "BAC": "BAC",
        "BEN": "BEN",
        "BK": "BK",
        "BLK": "BLK",
        "BRK-B": "BRKb.N",
        "C": "C",
        "CB": "CB",
        "CBOE": "CBOE.Z",
        "CFG": "CFG",
        "CINF": "CINF.OQ",
        "CMA": "CMA",
        "CME": "CME.OQ",
        "COF": "COF",
        "DFS": "DFS",
        "FITB": "FITB.OQ",
        "FRC": "FRC",
        "GL": "GL",
        "GS": "GS",
        "HBAN": "HBAN.OQ",
        "HIG": "HIG",
        "ICE": "ICE",
        "IVZ": "IVZ",
        "JPM": "JPM",
        "KEY": "KEY",
        "L": "L",
        "LNC": "LNC",
        "MA": "MA",
        "MCO": "MCO",
        "MET": "MET",
        "MKTX": "MKTX.OQ",
        "MMC": "MMC",
        "MS": "MS",
        "MSCI": "MSCI.N",
        "MTB": "MTB",
        "NDAQ": "NDAQ.OQ",
        "NTRS": "NTRS.OQ",
        "PBCT": "PBCT.OQ",
        "PFG": "PFG.OQ",
        "PGR": "PGR",
        "PNC": "PNC",
        "PRU": "PRU",
        "PYPL": "PYPL.OQ",
        "RE": "RE",
        "RF": "RF",
        "RJF": "RJF",
        "SCHW": "SCHW.N",
        "SIVB": "SIVB.OQ",
        "SPGI": "SPGI.N",
        "STT": "STT",
        "SYF": "SYF",
        "TFC": "TFC",
        "TROW": "TROW.OQ",
        "TRV": "TRV",
        "UNM": "UNM",
        "USB": "USB",
        "V": "V.N",
        "WFC": "WFC",
        "WLTW": "WLTW.OQ",
        "WRB": "WRB",
        "WU": "WU",
        "ZION": "ZION.OQ"
    },
    "Healthcare": {
        "A": "A",
        "ABBV": "ABBV.N",
        "ABC": "ABC",
        "ABMD": "ABMD.OQ",
        "ABT": "ABT",
        "ALGN": "ALGN.OQ",
        "ALXN": "ALXN.OQ",
        "AMGN": "AMGN.OQ",
        "ANTM": "ANTM.N",
        "BAX": "BAX",
        "BDX": "BDX",
        "BIIB": "BIIB.OQ",
        "BIO": "BIO",
        "BMY": "BMY",
        "BSX": "BSX",
        "CAH": "CAH",
        "CERN": "CERN.OQ",
        "CI": "CI",
        "CNC": "CNC",
        "COO": "COO",
        "CTLT": "CTLT.N",
        "CVS": "CVS",
        "DGX": "DGX",
        "DHR": "DHR",
        "DVA": "DVA",
        "DXCM": "DXCM.OQ",
        "EW": "EW",
        "GILD": "GILD.OQ",
        "HCA": "HCA",
        "HOLX": "HOLX.OQ",
        "HSIC": "HSIC.OQ",
        "HUM": "HUM",
        "IDXX": "IDXX.OQ",
        "ILMN": "ILMN.OQ",
        "INCY": "INCY.OQ",
        "IQV": "IQV",
        "ISRG": "ISRG.OQ",
        "JNJ": "JNJ",
        "LH": "LH",
        "LLY": "LLY",
        "MCK": "MCK",
        "MDT": "MDT",
        "MRK": "MRK",
        "MTD": "MTD",
        "PFE": "PFE",
        "PKI": "PKI",
        "PRGO": "PRGO.N",
        "REGN": "REGN.OQ",
        "RMD": "RMD",
        "STE": "STE",
        "SYK": "SYK",
        "TFX": "TFX",
        "TMO": "TMO",
        "UHS": "UHS",
        "UNH": "UNH",
        "VAR": "VAR",
        "VRTX": "VRTX.OQ",
        "VTRS": "VTRS.RTS",
        "WAT": "WAT",
        "WBA": "WBA.OQ",
        "WST": "WST",
        "XRAY": "XRAY.OQ",
        "ZBH": "ZBH",
        "ZTS": "ZTS"
    },
    "Industrials": {
        "AAL": "AAL.OQ",
        "ADP": "ADP.OQ",
        "ALK": "ALK",
        "ALLE": "ALLE.N",
        "AME": "AME",
        "AOS": "AOS",
        "AVY": "AVY",
        "BA": "BA",
        "CARR": "CARRA.MI",
        "CAT": "CAT",
        "CHRW": "CHRW.OQ",
        "CMI": "CMI",
        "CPRT": "CPRT.OQ",
        "CSX": "CSX.OQ",
        "CTAS": "CTAS.OQ",
        "DAL": "DAL",
        "DE": "DE",
        "DOV": "DOV",
        "EFX": "EFX",
        "EMR": "EMR",
        "ETN": "ETN",
        "EXPD": "EXPD.OQ",
        "FAST": "FAST.OQ",
        "FDX": "FDX",
        "FLS": "FLS",
        "GE": "GE",
        "GPN": "GPN",
        "GWW": "GWW",
        "HII": "HII",
        "HON": "HON",
        "HWM": "HWM",
        "IEX": "IEX",
        "INFO": "INFO.N",
        "IR": "IR",
        "ITW": "ITW",
        "J": "J",
        "JBHT": "JBHT.OQ",
        "JCI": "JCI",
        "KSU": "KSU",
        "LHX": "LHX",
        "LMT": "LMT",
        "LUV": "LUV",
        "MAS": "MAS",
        "MMM": "MMM",
        "NLSN": "NLSN.N",
        "NOC": "NOC",
        "NSC": "NSC",
        "ODFL": "ODFL.OQ",
        "OTIS": "ZOT.MC",
        "PAYX": "PAYX.OQ",
        "PCAR": "PCAR.OQ",
        "PH": "PH",
        "PNR": "PNR",
        "PWR": "PWR",
        "RHI": "RHI",
        "ROK": "ROK",
        "ROP": "ROP",
        "RSG": "RSG",
        "RTX": "RTX.CO",
        "SNA": "SNA",
        "SWK": "SWK",
        "TDG": "TDG",
        "TT": "TTG.L",
        "TXT": "TXT",
        "UAL": "UAL.OQ",
        "UNP": "UNP",
        "UPS": "UPS",
        "URI": "URI",
        "VRSK": "VRSK.OQ",
        "WAB": "WAB",
        "WM": "WM",
        "XYL": "XYL"
    },
    "Real Estate": {
        "AIRC": "AIRC.L",
        "AMT": "AMT",
        "ARE": "ARE",
        "AVB": "AVB",
        "BXP": "BXP",
        "CBRE": "CBRE.N",
        "CCI": "CCI",
        "DLR": "DLR",
        "DRE": "DRE",
        "EQIX": "EQIX.OQ",
        "EQR": "EQR",
        "ESS": "ESS",
        "EXR": "EXR",
        "FRT": "FRT",
        "HST": "HST.N",
        "IRM": "IRM",
        "KIM": "KIM",
        "MAA": "MAA",
        "O": "O",
        "PEAK": "PEAK.N",
        "PLD": "PLD",
        "PSA": "PSA",
        "REG": "REG.OQ",
        "SBAC": "SBAC.OQ",
        "SLG": "SLG",
        "SPG": "SPG",
        "UDR": "UDR",
        "VNO": "VNO",
        "VTR": "VTR",
        "WELL": "WELL.N",
        "WY": "WY"
    },
    "Technology": {
        "AAPL": "AAPL.OQ",
        "ACN": "ACN",
        "ADBE": "ADBE.OQ",
        "ADI": "ADI.OQ",
        "ADSK": "ADSK.OQ",
        "AKAM": "AKAM.OQ",
        "AMAT": "AMAT.OQ",
        "AMD": "AMD.OQ",
        "ANET": "ANET.N",
        "ANSS": "ANSS.OQ",
        "APH": "APH",
        "AVGO": "AVGO.OQ",
        "BR": "BR",
        "CDNS": "CDNS.OQ",
        "CDW": "CDW.OQ",
        "CRM": "CRM",
        "CSCO": "CSCO.OQ",
        "CTSH": "CTSH.OQ",
        "CTXS": "CTXS.OQ",
        "FFIV": "FFIV.OQ",
        "FINT": "FINT.TO",
        "FIS": "FIS",
        "FISV": "FISV.OQ",
        "FLT": "FLT",
        "FTV": "FTV",
        "GLW": "GLW",
        "GRMN": "GRMN.OQ",
        "HPE": "HPE",
        "HPQ": "HPQ",
        "IBM": "IBM",
        "INTC": "INTC.OQ",
        "INTU": "INTU.OQ",
        "IPGP": "IPGP.OQ",
        "IT": "IT",
        "JKHY": "JKHY.OQ",
        "KEYS": "KEYS.N",
        "KLAC": "KLAC.OQ",
        "LDOS": "LDOS.N",
        "LRCX": "LRCX.OQ",
        "MCHP": "MCHP.OQ",
        "MSFT": "MSFT.OQ",
        "MSI": "MSI",
        "MU": "MU.OQ",
        "MXIM": "MXIM.OQ",
        "NLOK": "NLOK.OQ",
        "NOW": "NOW",
        "NTAP": "NTAP.OQ",
        "NVDA": "NVDA.OQ",
        "ORCL": "ORCL.N",
        "PAYC": "PAYC.N",
        "QCOM": "QCOM.OQ",
        "QRVO": "QRVO.OQ",
        "SNPS": "SNPS.OQ",
        "STX": "STX.OQ",
        "SWKS": "SWKS.OQ",
        "TDY": "TDY",
        "TEL": "TEL",
        "TER": "TER.OQ",
        "TXN": "TXN.OQ",
        "TYL": "TYL",
        "VRSN": "VRSN.OQ",
        "WDC": "WDC.OQ",
        "XLNX": "XLNX.OQ",
        "ZBRA": "ZBRA.OQ"
    },
    "Utilities": {
        "AEE": "AEE",
        "AEP": "AEP.O",
        "AES": "AES",
        "ATO": "ATO",
        "AWK": "AWK",
        "CMS": "CMS",
        "CNP": "CNP",
        "D": "D",
        "DTE": "DTE",
        "DUK": "DUK",
        "ED": "ED",
        "EIX": "EIX",
        "ES": "ES",
        "ETR": "ETR",
        "EVRG": "EVRG.N",
        "EXC": "EXC.OQ",
        "FE": "FE",
        "LNT": "LNT.OQ",
        "NEE": "NEE",
        "NI": "NI",
        "NRG": "NRG",
        "PEG": "PEG",
        "PNW": "PNW",
        "PPL": "PPL",
        "SO": "SO",
        "SRE": "SRE",
        "WEC": "WEC",
        "XEL": "XEL.OQ"
    }
}